/**
 * Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefreshToken } from './refreshToken';
import { UserRole } from './userRole';


export interface AuthenticateResponse { 
    UserId?: number;
    UserName?: string | null;
    Role?: Array<UserRole> | null;
    OriginalUserName?: string | null;
    AccessToken?: string | null;
    RefreshToken?: RefreshToken;
}

